### ISSUE TITLE
[recommend] GPT-Runner: Conversations with your files! Manage and run your AI presets! 

### ISSUE THREAD

**Issue by 2214962083** [taishi-i/awesome-ChatGPT-repositories#23]
Github: https://github.com/nicepkg/gpt-runner

<img width="1438" alt="Screenshot 2023-07-15 at 23 22 03" src="https://github.com/taishi-i/awesome-ChatGPT-repositories/assets/35005637/c69c8cca-2e52-42af-8a41-6b3367a5b526">

**Comment by taishi-i** [comment]
Hi @2214962083! Thank you for your information proposal. I will add this information to the list next update. Also, I would like to add you as a contributor. Could you please send a pull request, using the next pull request as a reference? Please add the next line to the category you wish to add and send a pull request.

```
 * [Ultimate-ChatGPT](https://github.com/imabutahersiddik/Ultimate-ChatGPT) - The Ultimate ChatGPT is an AI-powered virtual assistant designed to provide an enhanced writing and problem-solving experience.
```

Reference:
https://github.com/taishi-i/awesome-ChatGPT-repositories/pull/20/files

If there's no need to add you as a contributor, I will add your repository, so no worries in that case. Thank you in advance.

**Comment by 2214962083** [comment]
@taishi-i 

Of course no problem, I will submit a pr to add gpt-runner for each language, since my gpt-runner has management prompt and cli and web and vscode extension at the same time, I request to put it in the prompt, so that More people know about it, hope you agree. Thank you !

**Comment by 2214962083** [comment]
The pr is created, thanks to review it: [https://github.com/taishi-i/awesome-ChatGPT-repositories/pull/24](https://github.com/taishi-i/awesome-ChatGPT-repositories/pull/24)

**Comment by 2214962083** [comment]
Thank you for your merge ! I think this can be closed
