### ISSUE TITLE
Can you add OCR GPT to your list ?

### ISSUE THREAD

**Issue by docduo** [taishi-i/awesome-ChatGPT-repositories#41]
**OCR**

Extract text and content from images or PDF documents

https://chat.openai.com/g/g-wETMBcESv-ocr

You can add the following to the productivity section for example 🙏🏻 
```
- [OCR](https://chat.openai.com/g/g-wETMBcESv-ocr): Extract text and content from images or PDF documents by [ocr.chat](https://get.ocr.chat/gpt)
```

- PR:

**Comment by taishi-i** [comment]
Hi @docduo! Thank you for the suggestion. At present, we are listing information on GitHub repositories. Therefore, GPTs are not covered for now. If there is any related code, it is possible to list that. Does it exist?
