### ISSUE TITLE
Request to change UnlimitedGPT URL

### ISSUE THREAD

**Issue by theAbdoSabbagh** [taishi-i/awesome-ChatGPT-repositories#50]
Hello,

I appreciate mentioning my project in this repository. However I have recently changed my username from `sxvxgee` to `theAbdoSabbagh`; thus I would appreciate it if the URL was updated.

Thank you,
abdo

**Comment by taishi-i** [comment]
Hi @theAbdoSabbagh. Thank you for submitting the issue. I got it. I will fix it in the next update, so please wait for a while. I will report again once the update is complete.

**Comment by taishi-i** [comment]
Hi @theAbdoSabbagh! I changed UnlimitedGPT URL in this repository. If this is OK, please close this issue. Thank you.
https://github.com/taishi-i/awesome-ChatGPT-repositories/blob/7ffa28083bfc5e69aba3d235676c569f00c43fb3/README.md?plain=1#L1174

**Comment by theAbdoSabbagh** [comment]
Hey there!

Thank you for updating the link, I really appreciate it. I was wondering about whether the spot of where my project is placed at is randomly chosen or if it is controlled by something like star count or such, as I would actuallt appreciate it if my project would be raised to the top for more exposure.

**Comment by taishi-i** [comment]
Hi @theAbdoSabbagh! No problem! I'm always looking forward to comments like this.

This list adds new repositories based on GitHub stars and recent update histories. Therefore, the information is presented in the order the repositories were added. For now, I am not considering changing the order of this list, but I am thinking about adding star statistics and providing a way to make information easier to find.
