### ISSUE TITLE
Add Yagc - Learn on-the-go 

### ISSUE THREAD

**Issue by imabutahersiddik** [taishi-i/awesome-ChatGPT-repositories#55]
YAGC is a dynamic mobile learning platform designed to enhance educational experiences. It provides users with access to a variety of resources, enabling learning on-the-go and fostering a flexible approach to education.

**Name**: Yagc
**URL**: [https://yagc.tahriver.online](https://yagc.tahriver.online)
**Platform**: Education, Online Learning, On-the-go

**Comment by taishi-i** [comment]
Hi @imabutahersiddik! Thank you for the suggestion. At present, we are listing information on GitHub repositories. Therefore, the web site is not covered for now. If there is any related code in GitHub, it is possible to list that. Does it exist?

**Comment by imabutahersiddik** [comment]
Peace and blessings be upon you,
This is a mistake that unable to recognize before opening issue that it is for repository. Yagc code are not open-source, so there is no repository of it.
