### ISSUE TITLE
UnleashedGPT, a ChatGPT jailbreak prompt

### ISSUE THREAD

**Issue by ambr0sial** [taishi-i/awesome-ChatGPT-repositories#9]
Hello! I am making a jailbreak prompt with friends called UnleashedGPT. If you would like to add it: https://github.com/ambr0sial/unleashedgpt
We're always updating the prompt to add new features and to prevent patches from OpenAI.

**Comment by taishi-i** [comment]
@ambr0sial Thank you for your proposal! I would like to add it to this list. I will include it in the next update and make it available in multiple languages. Please wait a little while.

**Comment by taishi-i** [comment]
Based on the information provided, I have published the repository. I have also translated it into multiple languages.
 
https://github.com/taishi-i/awesome-ChatGPT-repositories/blob/34c4ffadee112429b0ec3ba399467e9ebe2d8f34/README.md?plain=1#L23


If you have a website you would like to promote and would like to be added as a contributor, please edit the following line and send a pull request. Thank you in advance.

https://github.com/taishi-i/awesome-ChatGPT-repositories/blob/34c4ffadee112429b0ec3ba399467e9ebe2d8f34/README.md?plain=1#L56
